// components/MenuDropdown.tsx
import { FC, useState } from "react";
import ButtonContact from "./ButtonContact";
import MenuIcon from "./icons/MenuIcon";
import BookIcon from "./icons/BookIcon";
import PrinterIcon from "./icons/PrinterIcon";

type CertificateType = {
  link: string;
};

const MenuDropdown: FC<CertificateType> = ({ link }) => {
  const [isShow, setIsShow] = useState(false);
  return (
    <div className="inline-block cursor-pointer print:hidden">
      <div className="relative">
        <div className="text-red-800" onClick={() => setIsShow(!isShow)}>
          <ButtonContact Icon={MenuIcon} title="" />
        </div>

        <div
          className={`absolute z-10 duration-300 ${
            isShow ? "" : "h-0 overflow-hidden"
          }`}
        >
          <div className="grid-cols-2">
            <button onClick={() => print()}>
              <ButtonContact Icon={PrinterIcon} title="Print" />
            </button>
            <a target="_blank" rel="noreferrer" href={link}>
              <ButtonContact Icon={BookIcon} title="link" />
            </a>
            <a target="_blank" rel="noreferrer" href={link}>
              <ButtonContact Icon={BookIcon} title="link" />
            </a>
            <a target="_blank" rel="noreferrer" href={link}>
              <ButtonContact Icon={BookIcon} title="link" />
            </a>
            <a target="_blank" rel="noreferrer" href={link}>
              <ButtonContact Icon={BookIcon} title="link" />
            </a>
          </div>
        </div>
      </div>
    </div>
  );
};

export default MenuDropdown;

// src/components/MenuDropdown.svelte
<script>
  import ButtonContact from "./ButtonContact.svelte";
  import MenuIcon from "./icons/MenuIcon.svelte";
  import PrinterIcon from "./icons/PrinterIcon.svelte";
  import BookIcon from "./icons/BookIcon.svelte";

  export let link;
  let isShow = false;
</script>

<div class="inline-block cursor-pointer print:hidden">
      <div class="relative">
        <div class="text-red-800" on:click={() => isShow = !isShow}>
          <ButtonContact Icon={MenuIcon} title="" />
        </div>

        <div
          class={`absolute z-10 duration-500 overflow-hidden ${
            isShow ? "h-40" : "h-0"
          }`}
        >
          <div class="grid-cols-2">
            <button on:click={() => window.print()}>
              <ButtonContact Icon={PrinterIcon} title="Print" />
            </button>
            <a target="_blank" rel="noreferrer" href={link}>
              <ButtonContact Icon={BookIcon} title="link" />
            </a>
          </div>
        </div>
      </div>
    </div>
